apiVersion: v1
kind: ReplicationController
metadata:
  name: configsvr1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: configsvr1
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.3
          image: self/mongo_test
          name: configsvr1
          ports:
            - containerPort: 20000
          env:
            - name: CONFIGSVR
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: configsvr1
  labels:
    node: configsvr1
spec:
  ports:
    - port: 20000
  selector:
    node: configsvr1
