apiVersion: v1
kind: ReplicationController
metadata:
  name: mongos1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: mongos1
    spec:
      containers:
        - resources:
            limits:
#              cpu: 0.3
          image: self/mongo_test
          name: mongos1
          ports:
            - containerPort: 30000
          env:
            - name: MONGOS
              value: "true"
            - name : RepliSetName
              value: "rs0"
---
apiVersion: v1
kind: Service
metadata:
  name: mongos1
  labels:
    node: mongos1
spec:
  ports:
    - port: 30000
  selector:
    node: mongos1
