apiVersion: v1
kind: ReplicationController
metadata:
  name: rs1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        node: rs1
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.3
          image: self/mongo_test
          name: rs1
          ports:
            - containerPort: 27017
          env:
            - name: REPLISET
              value: "true"
            - name : RepliSetName
              value: "rs0"
---
apiVersion: v1
kind: Service
metadata:
  name: rs1
  labels:
    node: rs1
spec:
  ports:
    - port: 27017
  selector:
    node: rs1
